apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  namespace: backstage
  labels:
    app: nginx-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-app
  namespace: backstage
spec:
  selector:
    app: nginx-app
  ports:
  - name: http
    port: 80
    targetPort: 80