ingress:
  enabled: true
  className: "nginx"
  host: "backstage.localhost"
  path: "/"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

  tls:
    enabled: true
    secretName: "backstage-tls"

postgresql:
  enabled: true
  auth:
    database: backstage_db
    username: backstage_user
    password: supersecret123  # Change in production

backstage:
  appConfig:
    app:
      baseUrl: "https://backstage.localhost"
    backend:
      baseUrl: "https://backstage.localhost"
      listen:
        port: 7007
    auth:
      environment: development
      providers:
        guest: {}
    catalog:
      locations:
        - type: url
          target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/components/artist-lookup-component.yaml
    techdocs:
      builder: "local"
      generator:
        runIn: "local"
      publisher:
        type: "local"
  extraEnvVars:
    - name: NODE_ENV
      value: "development"
  resources:
    limits:
      cpu: "500m"
      memory: "1Gi"
    requests:
      cpu: "250m"
      memory: "512Mi"