app:
  baseUrl: http://localhost

backend:
  baseUrl: http://localhost:7007

service:
  type: NodePort

backstage:
  appConfig:
    app:
      title: Scaffolded Backstage App
      baseUrl: http://localhost:3000
    backend:
      baseUrl: http://localhost:7007
      listen:
        port: 7007
      database:
        client: better-sqlite3
        connection: ':memory:'
    techdocs:
      builder: 'local'
      generator:
        runIn: 'docker'
      publisher:
        type: 'local'
    auth:
      providers:
        guest:
          dangerouslyAllowOutsideDevelopment: true
    catalog:
      rules:
        - allow: [Component, System, API, Resource, Location]
      locations:
        - type: file
          target: examples/entities.yaml

logging:
  level: debug